### ISSUE TITLE
Plugin not working on Android SDK 33

### ISSUE THREAD

**Issue by davidgcs** [EYALIN/community-cordova-plugin-file-opener#1]
Hi, 

I'm using ionic 5

with the new android api I had to set my cdvTargetSdkVersion to 33 in the Gradle properties to support android 11+

The plugin is installed following the readme guidelines. It compiles with no issues and it's working with iOS when I try to upload an image for the user's profile in the app. 

The problem comes when I try to do the same on Android, it shows a log in console that says ```Error:  20``` when I try to call the camera plugin ```this.camera.pickFile(CameraSourceType.GALERY, CameraMediaType.ALL)```

```javascript
pickFile(sourceType, mediaType): Observable<string> {
    let cameraOptions = {
      destinationType: this.camera.DestinationType.DATA_URL,
      sourceType: this.camera.PictureSourceType.PHOTOLIBRARY,
      allowEdit: false,
      mediaType: 0,
      targetWidth: 512,
      targetHeight: 512
    };

    return from(this.camera.getPicture(cameraOptions)).pipe(
      map(res => {
        return 'data:image/jpeg;base64,' + res;
      })
    );
  }
``` 

I have checked the android permissions are set correctly in the android manifest

```
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
``` 

Is there anything I may be missing?

**Comment by davidgcs** [comment]
Seems to be a problem with targetSDK 33, it works fine with targetSDK 32

**Comment by EYALIN** [comment]
@davidgcs I will work on that.
we still can use targeting 32 for now until August.

thanks.

**Comment by EYALIN** [comment]
@davidgcs use Android permissions to get the permissions you need for Android 13. (READ_MEDIA_IMAGES, READ_MEDIA_VIDEO)

in your example, it's a camera plugin and not a file opener, but still, you will have the issue in both plugins.

**Comment by EYALIN** [comment]
need to use android permissions as a workaround
